/** Internal theme engine types — extends the public AmbientTheme contract */

import type { AmbientTheme } from '@/types'

/** CSS variable map generated by the ambient engine */
export type CSSVariableMap = Record<`--${string}`, string>

/** Theme transition state for smooth ambient switching */
export interface ThemeTransition {
  from: string | null
  to: string
  startedAt: number
  duration: number
}

/** Resolved runtime theme — AmbientTheme + computed CSS vars */
export interface ResolvedTheme extends AmbientTheme {
  cssVariables: CSSVariableMap
}

/** Registry entry for a preset theme */
export interface ThemePreset {
  theme: AmbientTheme
  /** Optional custom CSS to inject alongside variables */
  customCSS?: string
}

/** Ambient engine configuration */
export interface AmbientEngineConfig {
  /** Target element for CSS variable injection (default: document.documentElement) */
  targetElement?: HTMLElement
  /** Enable transition animations between themes */
  enableTransitions?: boolean
  /** Callback when theme changes complete */
  onTransitionEnd?: (themeId: string) => void
}
