#!/usr/bin/env bash
# ============================================================
# ShadowLink — Proto Code Generation (without buf)
# ============================================================
# Usage: ./generate.sh
#
# Requires: grpcio-tools (pip install grpcio-tools)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

PROTO_DIR="$SCRIPT_DIR"
PYTHON_OUT="$PROJECT_ROOT/shadowlink-ai/app/api/grpc/generated"

echo "═══════════════════════════════════════"
echo "ShadowLink Proto Generation"
echo "═══════════════════════════════════════"

# ── Python stubs ──
echo ""
echo "[Python] Generating gRPC stubs..."

mkdir -p "$PYTHON_OUT"

python -m grpc_tools.protoc \
    --proto_path="$PROTO_DIR" \
    --python_out="$PYTHON_OUT" \
    --grpc_python_out="$PYTHON_OUT" \
    --pyi_out="$PYTHON_OUT" \
    "$PROTO_DIR"/common.proto \
    "$PROTO_DIR"/agent_service.proto \
    "$PROTO_DIR"/rag_service.proto \
    "$PROTO_DIR"/mcp_service.proto \
    "$PROTO_DIR"/memory_service.proto

# Fix Python imports (protoc generates absolute imports, we need relative)
echo "[Python] Fixing imports..."
if [[ "$OSTYPE" == "darwin"* ]]; then
    SED_INPLACE="sed -i ''"
else
    SED_INPLACE="sed -i"
fi

for f in "$PYTHON_OUT"/*_pb2_grpc.py; do
    if [ -f "$f" ]; then
        $SED_INPLACE 's/^import \(.*_pb2\)/from . import \1/' "$f"
    fi
done

for f in "$PYTHON_OUT"/*_pb2.py; do
    if [ -f "$f" ]; then
        $SED_INPLACE 's/^import common_pb2/from . import common_pb2/' "$f"
    fi
done

# Create __init__.py
cat > "$PYTHON_OUT/__init__.py" << 'EOF'
"""Auto-generated gRPC stubs — do not edit manually."""
EOF

echo "[Python] Generated stubs in: $PYTHON_OUT"
echo ""

# ── Java stubs ──
echo "[Java] Proto stubs are generated by Maven protobuf-maven-plugin during build."
echo "       Run: cd shadowlink-server && ./mvnw compile"
echo ""

# ── Summary ──
echo "═══════════════════════════════════════"
echo "Generated files:"
ls -la "$PYTHON_OUT"/*.py 2>/dev/null || echo "  (no Python files generated)"
echo ""
echo "Done!"
